name: "Use Reusable Workflow"

on:
  push:
    branches:
      - main  # ✅ Trigger on push to main

jobs:
  call-create-secrets:
    uses: sarthaksharma22/template-automation-repo/.github/workflows/create_secrets.yml@main  # ✅ Correct path to reusable workflow
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}  # ✅ Ensure this secret exists in caller repo
