name: "Use Reusable Workflow"

on:
  push:
    branches:
      - main # ✅ Trigger on push to main

permissions:
  actions: write  # ✅ Allow reusable workflows to modify actions
  contents: read  # ✅ Allow reading repo contents

jobs:
  call-create-secrets:
    uses: sarthaksharma22/template-automation-repo/.github/workflows/create_secrets.yml@main
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}  # ✅ Ensure this secret exists
