name: "Use Reusable Secret Creation Workflow"

on:
  push:
    branches:
      - main

jobs:
  create-secrets:
    uses: sarthaksharma22/secrets-automation-template/.github/workflows/create-secrets.yml@main
    secrets:
      SECRET_1: ${{ secrets.SECRET_1 }}
      SECRET_2: ${{ secrets.SECRET_2 }}
      SECRET_3: ${{ secrets.SECRET_3 }}
