name: "Use Reusable Workflow"

on:
  push:
    branches:
      - main  # Trigger on push to main

jobs:
  call-create-secrets:
    uses: your-org-or-username/your-reusable-repo/.github/workflows/create-secrets.yml@main
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}  # Pass the PAT secret
