name: "Use Reusable Secret Creation Workflow"

on:
  push:
    branches:
      - main

jobs:
  create-secrets:
    uses: your-org/template-repo/.github/workflows/create-secrets.yml@main
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      SECRET_1: ${{ secrets.SECRET_1 }}
      SECRET_2: ${{ secrets.SECRET_2 }}
      SECRET_3: ${{ secrets.SECRET_3 }}
