name: "Use Reusable Secret Creation Workflow"

on:
  push:
    branches:
      - main

permissions:
  actions: write   # ✅ Allow reusable workflow to modify secrets
  contents: read   # ✅ Required to read repo content

jobs:
  create-secrets:
    uses: sarthaksharma22/secrets-automation-template/.github/workflows/create-secrets.yml@main
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      SECRET_1: ${{ secrets.SECRET_1 }}
      SECRET_2: ${{ secrets.SECRET_2 }}
      SECRET_3: ${{ secrets.SECRET_3 }}
